Project:      output/TinySoc_USB_UART
Build Number: 0
Date:         Wed Jul 03 09:44:04 2013
Compiler:     ICCM8C
Version:      7.05.00


Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             lit   01A0   01C2 =    450. bytes (rel,con,rom,lit)

       Addr  Global Symbol
      -----  --------------------------------
       01A0  _rsvp_lcd_str_blank
       01B1  _rsvp_lcd_str_version
       01C2  _rsvp_lcd_str_crlf
       01C5  USBUART_1_DEVICE_LOOKUP
       01CA  USBUART_1_D0_CONFIG_LOOKUP
       01D3  USBUART_1_D0_C1_INTERFACE_RPT_LOOKUP
       01D7  USBUART_1_D0_C1_HID_CLASS_DESCR_TABLE
       01F1  USBUART_1_DEVICE_DESCR_TABLE
       024F  USBUART_1_StringTable
       02B4  LoadConfigTBL_USB_Radon_Tiny_Bank0
       030F  LoadConfigTBL_USB_Radon_Tiny_Bank1
       0362  __lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                        func_lit   0362   0002 =      2. bytes (rel,con,rom,proclab)

       Addr  Global Symbol
      -----  --------------------------------
       0362  __func_lit_start
       0364  __func_lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     psoc_config   0364   014A =    330. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0364  LoadConfigTBL_USB_Radon_Tiny_Ordered
       0449  LoadConfigInit
       0449  _LoadConfigInit
       0453  LoadConfig_USB_Radon_Tiny
       0453  _LoadConfig_USB_Radon_Tiny
       04AE  __psoc_config_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     UserModules   04AE   0E24 =   3620. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       04AE  _USBUART_1_Not_Supported
       04AE  USBUART_1_CB_d2h_std_ifc_02
       04AE  USBUART_1_CB_h2d_std_ep_00
       04AE  USBUART_1_Not_Supported
       04AE  USBUART_1_CB_d2h_std_ifc_03
       04AE  USBUART_1_CB_h2d_std_dev_08
       04AE  USBUART_1_CB_h2d_std_ep_02
       04AE  USBUART_1_CB_h2d_std_dev_07
       04AE  USBUART_1_CB_d2h_std_ifc_04
       04AE  USBUART_1_CB_d2h_std_dev_07
       04AE  USBUART_1_CB_d2h_std_ifc_05
       04AE  USBUART_1_CB_h2d_std_dev_06
       04AE  USBUART_1_CB_d2h_std_ifc_06
       04AE  USBUART_1_CB_d2h_std_dev_05
       04AE  USBUART_1_CB_h2d_std_dev_04
       04AE  USBUART_1_CB_d2h_std_dev_04
       04AE  USBUART_1_CB_d2h_std_dev_03
       04AE  USBUART_1_CB_h2d_std_dev_02
       04AE  USBUART_1_CB_d2h_std_dev_02
       04AE  USBUART_1_CB_d2h_std_ifc_09
       04AE  USBUART_1_CB_d2h_std_dev_01
       04AE  USBUART_1_CB_d2h_std_ifc_07
       04AE  USBUART_1_CB_h2d_std_dev_00
       04AE  USBUART_1_CB_d2h_std_ifc_01
       04AE  USBUART_1_CB_d2h_std_ifc_08
       04AE  USBUART_1_CB_h2d_std_ifc_00
       04BE  USBUART_1_CB_d2h_std_dev_00
       04DF  USBUART_1_DT_d2h_std_dev_Dispatch
       04FF  USBUART_1_DT_h2d_std_dev_Dispatch
       0521  USBUART_1_DT_d2h_std_ifc_Dispatch
       0536  USBUART_1_DT_h2d_std_ifc_Dispatch
       054B  USBUART_1_DT_d2h_std_ep_Dispatch
       0570  USBUART_1_DT_h2d_std_ep_Dispatch
       0593  USBUART_1_CB_d2h_std_dev_06
       05F1  USBUART_1_CB_d2h_std_dev_08
       05FA  USBUART_1_CB_h2d_std_dev_01
       0605  USBUART_1_CB_h2d_std_dev_03
       061A  USBUART_1_CB_h2d_std_dev_05
       0623  USBUART_1_CB_h2d_std_dev_09
       067D  USBUART_1_CB_d2h_std_ifc_00
       0695  USBUART_1_CB_d2h_std_ifc_10
       06A9  USBUART_1_CB_d2h_std_ep_00
       06C2  USBUART_1_CB_h2d_std_ep_01
       06F7  USBUART_1_CB_h2d_std_ep_03
       0772  USBUART_1_EP0_ISR
       0772  _USBUART_1_EP0_ISR
       079A  USBUART_1_EP0_UPD_MODE_EXIT
       0811  _USBUART_1_InitControlRead
       0811  USBUART_1_InitControlRead
       084D  USBUART_1_NoDataStageControlTransfer
       084D  _USBUART_1_InitNoDataStageControlTransfer
       084D  USBUART_1_InitNoDataStageControlTransfer
       0858  _USBUART_1_InitControlWrite
       0858  USBUART_1_InitControlWrite
       0960  USBUART_1_GetTableEntry
       0986  USBUART_1_LOOKUP
       0994  USBUART_1_GETWORD
       099C  USBUART_1_GETBYTE
       09A5  USBUART_1_GET_DEVICE_TABLE_ENTRY
       09B6  USBUART_1_GET_CONFIG_TABLE_ENTRY
       09F4  USBUART_1_DT_bmRequestType
       0A34  USBUART_1_bmRequestType_Dispatch
       0A99  USBUART_1_DT_h2d_cls_ifc_Dispatch
       0AE9  USBUART_1_DT_d2h_cls_ifc_Dispatch
       0B51  USBUART_1_USB_EP_BIT_LOOKUP
       0B56  _USBUART_1_Start
       0B56  USBUART_1_Start
       0B93  _USBUART_1_Stop
       0B93  USBUART_1_Stop
       0BAC  USBUART_1_bCheckUSBActivity
       0BAC  _USBUART_1_bCheckUSBActivity
       0BC0  _USBUART_1_bGetRxCount
       0BC0  USBUART_1_bGetRxCount
       0BEE  USBUART_1_CWrite
       0BEE  _USBUART_1_CWrite
       0BF3  _USBUART_1_Write
       0BF3  USBUART_1_Write
       0C80  _USBUART_1_PutString
       0C80  USBUART_1_PutString
       0CA8  _USBUART_1_CPutString
       0CA8  USBUART_1_CPutString
       0CD4  _USBUART_1_PutChar
       0CD4  USBUART_1_PutChar
       0CE6  USBUART_1_PutCRLF
       0CE6  _USBUART_1_PutCRLF
       0CFD  USBUART_1_PutSHexByte
       0CFD  _USBUART_1_PutSHexByte
       0D1E  _USBUART_1_PutSHexInt
       0D1E  USBUART_1_PutSHexInt
       0D5C  _USBUART_1_Read
       0D5C  USBUART_1_Read
       0DED  USBUART_1_ReadAll
       0DED  _USBUART_1_ReadAll
       0E06  _USBUART_1_ReadChar
       0E06  USBUART_1_ReadChar
       0E1B  USBUART_1_bTxIsReady
       0E1B  _USBUART_1_bTxIsReady
       0E24  _USBUART_1_Init
       0E24  USBUART_1_Init
       0E7D  USBUART_1_dwGetDTERate
       0E7D  _USBUART_1_dwGetDTERate
       0EA1  USBUART_1_bGetCharFormat
       0EA1  _USBUART_1_bGetCharFormat
       0EA7  _USBUART_1_bGetParityType
       0EA7  USBUART_1_bGetParityType
       0EAD  USBUART_1_bGetDataBits
       0EAD  _USBUART_1_bGetDataBits
       0EB3  USBUART_1_bGetLineControlBitmap
       0EB3  _USBUART_1_bGetLineControlBitmap
       0EB9  _USBUART_1_SendStateNotify
       0EB9  USBUART_1_SendStateNotify
       0F1E  _USBUART_1_SetPowerStatus
       0F1E  USBUART_1_SetPowerStatus
       0F2E  _UART_1_TX_ISR
       0F2F  _UART_1_RX_ISR
       0FA3  _UART_1_EnableInt
       0FA3  UART_1_EnableInt
       0FAA  _UART_1_DisableInt
       0FAA  UART_1_DisableInt
       0FB1  _UART_1_SetTxIntMode
       0FB1  UART_1_SetTxIntMode
       0FC3  UART_1_Start
       0FC3  _UART_1_Start
       0FCC  UART_1_Stop
       0FCC  _UART_1_Stop
       0FD3  UART_1_SendData
       0FD3  _UART_1_SendData
       0FD6  _UART_1_bReadTxStatus
       0FD6  _bUART_1_ReadTxStatus
       0FD6  UART_1_bReadTxStatus
       0FD6  bUART_1_ReadTxStatus
       0FD9  UART_1_bReadRxData
       0FD9  _bUART_1_ReadRxData
       0FD9  _UART_1_bReadRxData
       0FD9  bUART_1_ReadRxData
       0FDC  _UART_1_bReadRxStatus
       0FDC  _bUART_1_ReadRxStatus
       0FDC  bUART_1_ReadRxStatus
       0FDC  UART_1_bReadRxStatus
       0FDF  UART_1_TxIntMode
       0FDF  _UART_1_TxIntMode
       0FF2  _UART_1_IntCntl
       0FF2  UART_1_IntCntl
       101D  _UART_1_PutSHexByte
       101D  UART_1_PutSHexByte
       1030  UART_1_PutSHexInt
       1030  _UART_1_PutSHexInt
       1037  _UART_1_PutChar
       1037  UART_1_PutChar
       103F  UART_1_cGetChar
       103F  _UART_1_cGetChar
       1047  _UART_1_cReadChar
       1047  UART_1_cReadChar
       105E  UART_1_iReadChar
       105E  _UART_1_iReadChar
       1074  _UART_1_PutString
       1074  UART_1_PutString
       1086  _UART_1_Write
       1086  UART_1_Write
       10AE  UART_1_CWrite
       10AE  _UART_1_CWrite
       10DA  _UART_1_CPutString
       10DA  UART_1_CPutString
       10EC  _UART_1_PutCRLF
       10EC  UART_1_PutCRLF
       10F5  UART_1_CmdReset
       10F5  _UART_1_CmdReset
       110B  _UART_1_bCmdCheck
       110B  UART_1_bCmdCheck
       1113  _UART_1_bErrCheck
       1113  UART_1_bErrCheck
       111E  UART_1_bCmdLength
       111E  _UART_1_bCmdLength
       1124  _UART_1_szGetParam
       1124  UART_1_szGetParam
       1182  _UART_1_szGetRestOfParams
       1182  UART_1_szGetRestOfParams
       118D  _SleepTimer_1_ISR
       11B0  SleepTimer_1_EnableInt
       11B0  _SleepTimer_1_EnableInt
       11B4  _SleepTimer_1_DisableInt
       11B4  SleepTimer_1_DisableInt
       11B8  SleepTimer_1_Start
       11B8  _SleepTimer_1_Start
       11CC  SleepTimer_1_Stop
       11CC  _SleepTimer_1_Stop
       11CD  SleepTimer_1_SetInterval
       11CD  _SleepTimer_1_SetInterval
       11E3  SleepTimer_1_TickWait
       11E3  _SleepTimer_1_TickWait
       11F5  SleepTimer_1_SyncWait
       11F5  _SleepTimer_1_SyncWait
       1206  SleepTimer_1_bGetTickCntr
       1206  _SleepTimer_1_bGetTickCntr
       120C  SleepTimer_1_SetTimer
       120C  _SleepTimer_1_SetTimer
       1212  _SleepTimer_1_bGetTimer
       1212  SleepTimer_1_bGetTimer
       1218  SleepTimer_1_iGetTickCntr
       1218  _SleepTimer_1_iGetTickCntr
       1226  _SleepTimer_1_lGetTickCntr
       1226  SleepTimer_1_lGetTickCntr
       124A  LED_1_On
       124A  _LED_1_On
       124E  LED_1_Start
       124E  _LED_1_Start
       124E  LED_1_Off
       124E  _LED_1_Off
       124E  LED_1_Stop
       124E  _LED_1_Stop
       1250  _LED_1_Switch
       1250  LED_1_Switch
       1268  LED_1_Invert
       1268  _LED_1_Invert
       1277  _LED_1_GetState
       1277  LED_1_GetState
       1287  _Counter8_1_ISR
       1288  _Counter8_1_EnableInt
       1288  Counter8_1_EnableInt
       128C  Counter8_1_DisableInt
       128C  _Counter8_1_DisableInt
       1290  _Counter8_1_Start
       1290  Counter8_1_Start
       1294  _Counter8_1_Stop
       1294  Counter8_1_Stop
       1298  Counter8_1_WritePeriod
       1298  _Counter8_1_WritePeriod
       129B  Counter8_1_WriteCompareValue
       129B  _Counter8_1_WriteCompareValue
       129E  _bCounter8_1_ReadCompareValue
       129E  bCounter8_1_ReadCompareValue
       129E  _Counter8_1_bReadCompareValue
       129E  Counter8_1_bReadCompareValue
       12A1  _bCounter8_1_ReadCounter
       12A1  Counter8_1_bReadCounter
       12A1  bCounter8_1_ReadCounter
       12A1  _Counter8_1_bReadCounter
       12D2  __UserModules_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            text   12D2   04B7 =   1207. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       12D2  __text_start
       12D2  _main
       12E4  _RSVP_USBUART_Echo
       1334  _RSVP_USBUART_Send_Greeting
       135F  _RSVP_blinkVersion
       13C1  _RSVP_USBUART_Initialize
       13DA  _RSVP_UART_Initialize
       13FF  _RSVP_UART_1_Config
       16F1  _SleepTimer_1_ISRV
       16F7  _RSVP_Initialize
       1752  USBUART_1_EP1_ISR
       1752  _USBUART_1_EP1_ISR
       1756  USBUART_1_EP2_ISR
       1756  _USBUART_1_EP2_ISR
       175A  USBUART_1_EP3_ISR
       175A  _USBUART_1_EP3_ISR
       175E  USBUART_1_EP4_ISR
       175E  _USBUART_1_EP4_ISR
       1762  _USBUART_1_RESET_ISR
       1762  USBUART_1_RESET_ISR
       1787  _USBUART_1_SOF_ISR
       1787  USBUART_1_SOF_ISR
       1788  USBUART_1_WAKEUP_ISR
       1788  _USBUART_1_WAKEUP_ISR
       1789  __xidata_start
       1789  __text_end
       179B  __xidata_end

Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             TOP   0000   013B =    315. bytes (abs,ovr,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0068  __Start
       0138  _bGetPowerSetting
       0138  bGetPowerSetting

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                    InterruptRAM   0000   0044 =     68. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  _USBUART_1_bCurrentDevice
       0000  USBUART_1_bCurrentDevice
       0001  USBUART_1_Configuration
       0001  _USBUART_1_Configuration
       0002  USBUART_1_DeviceStatus
       0002  _USBUART_1_DeviceStatus
       0003  USBUART_1_InterfaceSetting
       0003  _USBUART_1_InterfaceSetting
       0005  _USBUART_1_EndpointStatus
       0005  USBUART_1_EndpointStatus
       000A  USBUART_1_LastSize
       000B  USBUART_1_TransferType
       000C  USBUART_1_TransferBuffer
       0014  _USBUART_1_CurrentTD
       0014  USBUART_1_CurrentTD
       0014  USBUART_1_DataSource
       0014  _USBUART_1_DataSource
       0015  USBUART_1_TransferSize
       0015  _USBUART_1_TransferSize
       0017  _USBUART_1_DataPtr
       0017  USBUART_1_DataPtr
       0019  USBUART_1_StatusBlockPtr
       0019  _USBUART_1_StatusBlockPtr
       001D  _USBUART_1_EPDataToggle
       001D  USBUART_1_EPDataToggle
       001E  USBUART_1_fDataPending
       001F  USBUART_1_t2
       0020  USBUART_1_t1
       0021  USBUART_1_t0
       0022  USBUART_1_EndpointAPIStatus
       0022  _USBUART_1_EndpointAPIStatus
       002F  _USBUART_1_LineCoding
       002F  USBUART_1_LineCoding
       0036  USBUART_1_LineControlBitmap
       0036  _USBUART_1_LineControlBitmap
       0038  USBUART_1_APITemp
       003A  UART_1_fStatus
       003A  _UART_1_fStatus
       003B  _UART_1_bRxCnt
       003B  UART_1_bRxCnt
       003C  _SleepTimer_1_fTick
       003C  SleepTimer_1_fTick
       003D  SleepTimer_1_bTimerValue
       003D  _SleepTimer_1_bTimerValue
       003E  _SleepTimer_1_bCountDown
       003E  SleepTimer_1_bCountDown
       003F  SleepTimer_1_TickCount
       003F  _SleepTimer_1_TickCount
       0043  NO_SHADOW
       0043  _Port_1_Data_SHADE
       0043  _NO_SHADOW
       0043  Port_1_Data_SHADE

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                      UART_1_RAM   0000   0011 =     17. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       00A5  UART_1_aRxBuffer
       00A5  _UART_1_aRxBuffer

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
               virtual_registers   00BF   0003 =      3. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       00BF  __rY
       00C0  __r1
       00C1  __r0

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            data   0000   0076 =    118. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  __data_start
       0044  _USB_Buffer
       0084  _pData
       00B5  _ReadData
       00C2  _delay
       00C4  _loop
       00C6  _strPtr
       00C8  _Data1
       00C9  _USB_Count
       00CA  _USB_VDD_Counter
       00CB  _len
       00CD  _VDD_ON

Files Linked      [ module(s) ]

./obj/boot.o	[ boot.asm ]
obj/main.o	[ main.c ]
<library>	[ usbuart_1int.asm, usbuart_1_std.asm, usbuart_1_drv.asm, usbuart_1_descr.asm, usbuart_1_cls_cdc.asm ]
[ usbuart_1.asm, uart_1int.asm, uart_1.asm, sleeptimer_1int.asm, sleeptimer_1.asm, psocconfigtbl.asm ]
[ psocconfig.asm, led_1.asm, counter8_1int.asm, counter8_1.asm, rY.asm, r1.asm, r0.asm ]

Area Definitions

-blit:0x1a0.0x3fff
-bdata:0.0x2ff
-BInterruptRAM:0	allocated at: 0
-Bvirtual_registers	allocated at: 0xbf
-BUSB_Radon_Tiny_RAM
-rwh:SSCParmBlk:0xf7.0xff

