/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x4
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x5
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x8
#pragma	ioport	LED_1Pin_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_1Pin_MUXBusCtrl_ADDR;
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// TX address and mask defines
#pragma	ioport	TX_Data_ADDR:	0x4
BYTE			TX_Data_ADDR;
#pragma	ioport	TX_DriveMode_0_ADDR:	0x104
BYTE			TX_DriveMode_0_ADDR;
#pragma	ioport	TX_DriveMode_1_ADDR:	0x105
BYTE			TX_DriveMode_1_ADDR;
#pragma	ioport	TX_DriveMode_2_ADDR:	0x7
BYTE			TX_DriveMode_2_ADDR;
#pragma	ioport	TX_GlobalSelect_ADDR:	0x6
BYTE			TX_GlobalSelect_ADDR;
#pragma	ioport	TX_IntCtrl_0_ADDR:	0x106
BYTE			TX_IntCtrl_0_ADDR;
#pragma	ioport	TX_IntCtrl_1_ADDR:	0x107
BYTE			TX_IntCtrl_1_ADDR;
#pragma	ioport	TX_IntEn_ADDR:	0x5
BYTE			TX_IntEn_ADDR;
#define TX_MASK 0x20
#pragma	ioport	TX_MUXBusCtrl_ADDR:	0x1d9
BYTE			TX_MUXBusCtrl_ADDR;
// TX Shadow defines
//   TX_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define TX_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// RX address and mask defines
#pragma	ioport	RX_Data_ADDR:	0x4
BYTE			RX_Data_ADDR;
#pragma	ioport	RX_DriveMode_0_ADDR:	0x104
BYTE			RX_DriveMode_0_ADDR;
#pragma	ioport	RX_DriveMode_1_ADDR:	0x105
BYTE			RX_DriveMode_1_ADDR;
#pragma	ioport	RX_DriveMode_2_ADDR:	0x7
BYTE			RX_DriveMode_2_ADDR;
#pragma	ioport	RX_GlobalSelect_ADDR:	0x6
BYTE			RX_GlobalSelect_ADDR;
#pragma	ioport	RX_IntCtrl_0_ADDR:	0x106
BYTE			RX_IntCtrl_0_ADDR;
#pragma	ioport	RX_IntCtrl_1_ADDR:	0x107
BYTE			RX_IntCtrl_1_ADDR;
#pragma	ioport	RX_IntEn_ADDR:	0x5
BYTE			RX_IntEn_ADDR;
#define RX_MASK 0x80
#pragma	ioport	RX_MUXBusCtrl_ADDR:	0x1d9
BYTE			RX_MUXBusCtrl_ADDR;
// RX Shadow defines
//   RX_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define RX_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
